services:
  frontend-insta:
    container_name: frontend-insta
    restart: always
    build: frontend-insta
    volumes:
      - ./frontend-insta:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend-flask
    networks:
      - react-flask
    ports:
      - 3000:3000
    stdin_open: true

  backend-flask:
    container_name: backend-flask
    restart: always
    build: backend-flask
    volumes:
      - ./backend-flask:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - flask-mongo
      - react-flask
    ports:
      - "8080:8080"
    expose: 
      - 3000

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - flask-mongo
    expose:
      - 27017
networks:
  react-flask:
  flask-mongo: